/*

 SPR_MARTIN_DOWN0.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spr_Martin_down0Bank 0
extern unsigned char spr_Martin_down0TLE0[];
extern unsigned char spr_Martin_down0TLE1[];
extern unsigned char spr_Martin_down0TLE2[];
extern unsigned char spr_Martin_down0TLE3[];

/* End of SPR_MARTIN_DOWN0.H */
