/*

 EXAMPLE_NPC.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define example_NPCBank 0
extern unsigned char spr_example_NPC_00[];
extern unsigned char spr_example_NPC_01[];
extern unsigned char spr_example_NPC_10[];
extern unsigned char spr_example_NPC_11[];

/* End of EXAMPLE_NPC.H */
